# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x04test\"B\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07picture\x18\x03 \x01(\x0c\x12\r\n\x05works\x18\x04 \x03(\t\"\'\n\x05Pizza\x12\x0c\n\x04size\x18\x01 \x01(\t\x12\x10\n\x08toppings\x18\x02 \x03(\tB\tZ\x07../testb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007../test'
  _AUTHOR._serialized_start=23
  _AUTHOR._serialized_end=89
  _PIZZA._serialized_start=91
  _PIZZA._serialized_end=130
# @@protoc_insertion_point(module_scope)
